# https://github.com/slackapi/slack-github-action

name: "Send notification to Slack"
on:
  workflow_dispatch:
    inputs:
      message:
        description: "Message to send to Slack"
        required: true
        type: string
defaults:
  run:
    shell: bash

jobs:
  send_notification:
    name: Slack notify
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Send notification to Slack
        uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: ${{ inputs.message }}
